-- ⚠️ ATTENTION : CE SCRIPT RÉINITIALISE LA TABLE CONTACTS ⚠️
-- Exécutez-le dans l'éditeur SQL de Supabase pour repartir sur des bases saines et sécurisées.

-- 1. Nettoyage (Supprime l'ancienne table et ses données !)
DROP TABLE IF EXISTS public.contacts;

-- 2. Création de la table (Structure optimisée pour le formulaire)
CREATE TABLE public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  first_name text not null,
  last_name text not null,
  email text not null, 
  message text not null,
  metadata jsonb default '{}'::jsonb
);

-- 3. Activation de la Sécurité (RLS)
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

-- 4. Politique d'INSERTION (Publique)
-- Permet à n'importe qui (le formulaire du site) d'envoyer un message.
CREATE POLICY "Envoi public pour tout le monde" 
ON public.contacts 
FOR INSERT 
TO public 
WITH CHECK (true);

-- 5. Politique de LECTURE (Privée/Authentifiée)
-- Permet de lire les messages uniquement si vous êtes connecté (ex: via le dashboard ou une future app admin).
CREATE POLICY "Lecture pour admins seulement" 
ON public.contacts 
FOR SELECT 
TO authenticated 
USING (true);
